-- AlterEnum
-- Add new values to CropType enum
ALTER TYPE "CropType" ADD VALUE IF NOT EXISTS 'POTATOES';
ALTER TYPE "CropType" ADD VALUE IF NOT EXISTS 'CASSAVA';
ALTER TYPE "CropType" ADD VALUE IF NOT EXISTS 'RICE';
ALTER TYPE "CropType" ADD VALUE IF NOT EXISTS 'SUGARCANE';
